name: TOC Generator
run-name: TOC Generator [${{ github.ref_name }}]
on: push
jobs:
  generateTOC:
    name: TOC Generator
    runs-on: ubuntu-latest
    steps:
      - uses: technote-space/toc-generator@v4
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MAX_HEADER_LEVEL: 2
          COMMIT_MESSAGE: "Auto update TOC"
